# Generated by Django 5.1.2 on 2025-04-25 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mynews", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userarticleinteraction",
            name="article",
        ),
        migrations.RemoveField(
            model_name="userarticleinteraction",
            name="user",
        ),
        migrations.DeleteModel(
            name="Article",
        ),
        migrations.DeleteModel(
            name="UserArticleInteraction",
        ),
    ]
