# Generated by Django 5.1.2 on 2025-04-25 06:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mynews", "0002_remove_userarticleinteraction_article_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("writer", models.TextField()),
                ("write_date", models.DateTimeField()),
                ("category", models.TextField()),
                ("content", models.TextField()),
                ("url", models.TextField(unique=True)),
                (
                    "embedding",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=None
                    ),
                ),
                (
                    "keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
            ],
            options={
                "db_table": "news_article",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("keywords", models.JSONField(default=list)),
                ("write_date", models.DateTimeField(auto_now_add=True)),
                ("writer", models.CharField(max_length=100)),
                ("url", models.URLField(blank=True, null=True)),
                ("article_interaction", models.JSONField(default=dict)),
            ],
        ),
    ]
