# Generated by Django 5.1.2 on 2025-04-25 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mynews", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"managed": False},
        ),
    ]
